[font]
size = 10.5

[font.normal]
family = "Source Code Pro for Powerline"
style = "Regular"

[terminal.shell]
program = "/usr/bin/fish"
args = ["-l", "-c", "zellij attach --index 0 --create"]

[window]
dimensions = { columns = 150, lines = 60 }
opacity = 0.9
startup_mode = "Maximized"
