[tools]
cargo-binstall = "latest"
"cargo:alacritty" = "latest"
cmake = "latest"
codex = "latest"
delta = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
lazygit = "latest"
node = "latest"
ripgrep = "latest"
rust = "latest"
tokei = "latest"
uv = "latest"
zellij = "latest"
zig = "latest"
zoxide = "latest"
