model = "gpt-5.4"
model_reasoning_effort = "medium"
personality = "pragmatic"
network_access = true
notify = [
    "bash",
    "-lc",
    "paplay /usr/share/sounds/freedesktop/stereo/complete.oga",
]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.serena]
command = "uvx"
args = [
    "--from",
    "git+https://github.com/oraios/serena",
    "serena",
    "start-mcp-server",
    "--context",
    "codex",
]
